Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -27,7 +27,7 @@ jobs:
           if [[ $(wc -l sample.txt) -ge "3" ]]; then
             echo "It worked!";
           else
-            echo "Nope!"; exit 1
+            echo "It has Failed"; exit 1
           fi
           
 workflows:
